#!/usr/bin/env bash

###################################################################################
#                                                                                 #
#  Copyright (c) 2020 Natanael Barbosa Santos                                     #
#                                                                                 #
#  Permission is hereby granted, free of charge, to any person obtaining a copy   #
#  of this software and associated documentation files (the "Software"), to deal  #
#  in the Software without restriction, including without limitation the rights   #
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell      #
#  copies of the Software, and to permit persons to whom the Software is          #
#  furnished to do so, subject to the following conditions:                       #
#                                                                                 #
#  The above copyright notice and this permission notice shall be included in     #
#  all copies or substantial portions of the Software.                            #
#                                                                                 #
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR     #
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,       #
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE    #
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER         #
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,  #
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN      #
#  THE SOFTWARE.                                                                  #
#                                                                                 #
###################################################################################



[ "${1}" = "-n" ] && {
  shift
  strace -efile ${@} 2>&1 | grep -E "NOENT" | cut -d\" -f2 | grep ^"/"
  exit ${?}
}

[ "${1}" = "-a" ] && {
  shift
  strace -efile ${@} 2>&1 | cut -d\" -f2 | grep ^"/"
  exit ${?}
}

[ "${1}" = "-e" ] && {
  shift
  strace -efile ${@} 2>&1 | grep -Ev "NOENT" | cut -d\" -f2 | grep ^"/"
  exit ${?}
}

[ "${1}" = "-h" ] && {
  echo -e "usage: strace-file [option] PROG [ARGS]\n"
  echo "Options:"
  echo "  -n    Prints only non existing files"
  echo "  -a    Prints both nonexistent and existing files"
  echo "  -e    Prints only existing files (default behaviour)"
  echo "  -v    Prints version of strace-file"
  exit 0
}

[ "${1}" = "-v" ] && {
  echo -e "strace-file: Copyright (c) 2020 Natanael Barbosa Santos"
  echo -e "Version: 1.0"
  exit 0
}

[ "${1}" = "" ] && {
  echo "strace-file: must have at least PROG [ARGS]" 1>&2
  echo "Try 'strace -h' for more information." 1>&2
  exit 1
}

  strace -efile ${@} 2>&1 | grep -Ev "NOENT" | cut -d\" -f2 | grep ^"/"
  exit ${?}


