#!/usr/bin/env bash

HERE="$(dirname "$(readlink -f "${0}")")"
export LIBRARY_PATH="$HERE/usr/lib/x86_64-linux-gnu"
export LIBRARY_PATH="$HERE/lib/x86_64-linux-gnu":$LIBRARY_PATH

function strace_tool(){
  [ -f "${HERE}/lib64/ld-linux-x86-64.so.2" ] && {
    exec "${HERE}/lib64/ld-linux-x86-64.so.2" --inhibit-cache --library-path "${LIBRARY_PATH}" "${HERE}/usr/bin/strace" -efile ${@}
    return ${?}
  }
  strace -efile ${@}
  return ${?}
}

[ "${1}" = "-n" ] && {
  shift
  strace_tool ${@} 2>&1 | grep -E "NOENT" | cut -d\" -f2 | grep ^"/"
  exit ${?}
}

[ "${1}" = "-a" ] && {
  shift
  strace_tool ${@} 2>&1 | cut -d\" -f2 | grep ^"/"
  exit ${?}
}

[ "${1}" = "-e" ] && {
  shift
  strace_tool ${@} 2>&1 | grep -Ev "NOENT" | cut -d\" -f2 | grep ^"/"
  exit ${?}
}

[ "${1}" = "-h" ] && {
  echo -e "usage: strace-file [option] PROG [ARGS]\n"
  echo "Options:"
  echo "  -n    Prints only non existing files"
  echo "  -a    Prints both nonexistent and existing files"
  echo "  -e    Prints only existing files (default behaviour)"
  echo "  -v    Prints version of strace-file"
  exit 0
}

[ "${1}" = "-v" ] && {
  echo -e "strace-file: Copyright (c) 2020 Natanael Barbosa Santos"
  echo -e "Version: 1.0"
  exit 0
}

[ "${1}" = "" ] && {
  echo "strace-file: must have at least PROG [ARGS]" 1>&2
  echo "Try 'strace -h' for more information." 1>&2
  exit 1
}

  strace_tool ${@} 2>&1 | grep -Ev "NOENT" | cut -d\" -f2 | grep ^"/"
  exit ${?}


